<?php

/**
 * @file
 * Custom elements hooks.
 */

use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Render\Element;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function custom_elements_theme() {
  return [
    'custom_elements' => [
      'tag' => NULL,
      'tag_prefix' => NULL,
      'attributes' => NULL,
      'slots' => [],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_alter().
 *
 * Use custom elements template for every content entity which is using
 * view mode prefixed with `custom_elements`.
 */
function custom_elements_theme_suggestions_alter(array &$suggestions, array &$variables, $hook) {
  // Applies if view mode is prefixed with 'custom_elements'.
  if (isset($variables['elements']['#view_mode']) && strpos($variables['elements']['#view_mode'], 'custom_elements') === 0) {
    // Suggests that hook is entity type, so entity object is placed on #{hook}.
    $entity = $variables['elements']['#' . $hook] ?? NULL;
    // Check if entity was found.
    if (!$entity) {
      /** @var \Drupal\Core\Logger\LoggerChannel $logger */
      $logger = \Drupal::service('logger.channel.custom_elements');
      $logger->warning(t('Cannot obtain entity @entity for element with custom elements view mode.', ['@entity' => $hook]));
      return;
    }
    // Check if entity is content entity, exit if not.
    if (!$entity instanceof ContentEntityBase) {
      return;
    }
    $variables['elements']['#entity'] = $entity;
    $suggestions[] = 'custom_elements';
  }
}

/**
 * Prepares variables for an entity that is rendered as custom element.
 *
 * Default template: custom-elements.twig.html.
 */
function template_preprocess_custom_elements(&$variables) {
  /** @var \Drupal\Core\Entity\ContentEntityBase $entity */
  $entity = $variables['elements']['#entity'];
  // Attach custom-elements libraries.
  $variables['#attached']['library'][] = 'custom_elements/main';

  /** @var \Drupal\custom_elements\Service\CustomElementGenerator $generator */
  $generator = \Drupal::service('custom_elements.generator');
  $field_names = Element::children($variables['elements']);
  $custom_element = $generator->generate($entity, $field_names, $variables['elements']['#view_mode']);

  // Allow altering the element before its output.
  \Drupal::moduleHandler()->alter('custom_element', $custom_element);

  $variables['attributes'] = new Attribute($custom_element->getAttributes());
  $variables['slots'] = $custom_element->getSlots();
  $variables['tag_prefix'] = $custom_element->getTagPrefix();
  $variables['tag'] = $custom_element->getTag();
}
