<template>
  <div>
    <slot>
      <component :is="useDrupalCe().renderCustomElements(content)" />
    </slot>
  </div>
</template>
  
<script setup lang="ts">
defineProps<{
  /**
   * HTML content to render when no slot content is provided.
   * Required if no default slot content is used.
   */
  content?: string
}>()

// This component makes sure we have some default output for "field-*" custom elements like
// image fields during development. "field-* elements are often generated by custom-elements
// when it's simply configured to do automatic processing.
defineSlots<{
  default(): any
}>()
</script>
