<template>
  <div>
    <slot>
      <component :is="useDrupalCe().renderCustomElements(content)" />
    </slot>
  </div>
</template>
  
<script setup lang="ts">
import type { CustomElementContent } from 'nuxtjs-drupal-ce'

defineProps<{
  /**
   * Custom elements content to render.
   * Required if no default slot content is used.
   */
  content?: CustomElementContent
}>()

// This component makes sure we have some default output for "field-*" custom elements like
// image fields during development. "field-* elements are often generated by custom-elements
// when it's simply configured to do automatic processing.
defineSlots<{
  default(): any
}>()
</script>
