export default defineEventHandler(() => [
  { 
    key: '06c57f70-be51-4fa4-a944-a71704a616df', 
    title: 'Another page', 
    description: null, 
    uri: 'node\/3', 
    alias: 'node\/3', 
    external: false, 
    absolute: 'https:\/\/8080-drunomics-lupusdecouple-fd0ilwlpax7.ws-eu84.gitpod.io\/node\/3', 
    relative: '\/node\/3', 
    existing: true, 
    weight: '0', 
    expanded: false, 
    enabled: true, 
    uuid: 'b49a069f-1d05-4a54-a201-c7d06605f7c5', 
    options: [] 
  },
  { 
    key: '819c0178-ee38-4778-b489-2eedc4c20249', 
    title: 'Test page', 
    description: null, 
    uri: 'node\/1', 
    alias: 'node\/1', 
    external: false, 
    absolute: 'https:\/\/8080-drunomics-lupusdecouple-fd0ilwlpax7.ws-eu84.gitpod.io\/node\/1', 
    relative: '\/node\/1', 
    existing: true, 
    weight: '0', 
    expanded: false, 
    enabled: true, 
    uuid: '98f6edd6-42d1-44ac-a154-3e23895dcfc9', 
    options: [] 
  },
  {
    key: 'redirecting-page',
    title: 'Redirecting page',
    description: null,
    uri: 'redirect-to-3',
    alias: 'redirect-to-3',
    external: false,
    absolute: 'https:\/\/8080-drunomics-lupusdecouple-fd0ilwlpax7.ws-eu84.gitpod.io\/redirect-to-3',
    relative: '\/redirect-to-3',
    existing: true,
    weight: '0',
    expanded: false,
    enabled: true,
    uuid: 'redirecting-page',
    options: []
  },
  {
    key: 'states-form-demo',
    title: 'Conditional form',
    description: null,
    uri: 'form\/states',
    alias: 'form\/states',
    external: false,
    absolute: 'https:\/\/8080-drunomics-lupusdecouple-fd0ilwlpax7.ws-eu84.gitpod.io\/form\/states',
    relative: '\/form\/states',
    existing: true,
    weight: '0',
    expanded: false,
    enabled: true,
    uuid: 'states-form-demo',
    options: []
  },
  {
    key: 'layout-builder-demo',
    title: 'Layout',
    description: null,
    uri: 'node\/layout-builder',
    alias: 'node\/layout-builder',
    external: false,
    absolute: 'https:\/\/8080-drunomics-lupusdecouple-fd0ilwlpax7.ws-eu84.gitpod.io\/node\/layout-builder',
    relative: '\/node\/layout-builder',
    existing: true,
    weight: '0',
    expanded: false,
    enabled: true,
    uuid: 'layout-builder-demo',
    options: []
  }
])