name: ci

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Todo: Fix tests on windows and re-enable.
        os: [ubuntu-latest, macos-latest]
        node: [12, 14]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Coverage
        uses: drunomics/codecov-action@v1
